server:
    servlet:
        context-path: /
    port: 8080

spring:
    profiles: dev
    thymeleaf:
        servlet:
            content-type: text/html;charset=UTF-8
        prefix: classpath:/templates/
        suffix: .html
        cache: false
        encoding: UTF-8





